import { lesson as l, section as s, example as e, question as q } from "./helpers.js";

export const additionalLessons = {
  start: [
    l("start-language", "Palavras, frases e pequenas conexões", 7, "Entender o vocabulário usado nas explicações, mesmo sem lembrar das aulas de gramática.", [
      s("Uma palavra dá nome a uma ideia", "Antes de olhar os símbolos, pense em português: água, livro e estudante dão nome a coisas ou pessoas. Chamamos essas palavras de substantivos. Em japonês, 水 (mizu) é água e 本 (hon) é livro. A escrita parece nova, mas a ideia de dar nome a algo você já conhece.", [e("水", "みず", "mizu", "água"), e("本", "ほん", "hon", "livro")], "Leitura é como você pronuncia a palavra. Tradução é o que ela quer dizer. São informações diferentes."),
      s("Uma frase conecta essas ideias", "Beber é uma ação: a palavra que expressa essa ação é um verbo. Em “bebo água”, água é o que eu bebo, chamado de objeto direto. Nos modelos iniciais em japonês, a ação aparece no final. Não traduza colocando cada palavra na mesma posição do português.", [e("水を飲みます。", "みずをのみます。", "mizu o nomimasu", "Bebo água.", "水 = água; を mostra o que é bebido; 飲みます = bebo / vou beber.")]),
      s("Partículas funcionam como etiquetas", "Uma partícula é uma palavra curta que indica uma relação. Ela costuma vir depois do trecho que marca. は apresenta o assunto; を mostra o objeto nestes exemplos. Você não precisa decorar todos os nomes agora: abra “Em outras palavras” quando um termo parecer novo.", [e("わたしは学生です。", "わたしはがくせいです。", "watashi wa gakusei desu", "Eu sou estudante.", "わたし = eu; は = falando de mim; 学生 = estudante; です encerra esta afirmação com educação.")])
    ], [q("O que significa “leitura de uma palavra”?", ["Como ela é pronunciada", "Quantos traços ela tem", "A sua tradução"], 0, "Leitura indica a pronúncia. 水 se lê mizu e significa água."), q("Em 水を飲みます, o que é bebido?", ["飲みます", "水", "を"], 1, "水 é água. を vem depois e mostra que água é o objeto da ação de beber."), q("Onde fica o verbo nos modelos iniciais?", ["Sempre no começo", "Antes do objeto", "No final da frase"], 2, "Água + を + beber: 水を飲みます. Aos poucos você vai se acostumar com essa ordem.")], { route: "glossary", label: "Explorar as explicações" }),
    l("start-study", "Como praticar sem se perder", 5, "Criar uma rotina de leitura, escuta, escrita e revisão em passos pequenos.", [
      s("Escolha pouco e faça algo com isso", "Comece pelas cinco vogais do hiragana. Olhe um caractere, ouça, diga o som e tente lembrar sem olhar a resposta. Estudar cinco caracteres com atenção é mais útil do que passar os olhos pela tabela inteira. O botão de áudio toca uma pronúncia de apoio; você pode diminuir a velocidade em Meu ritmo.", [e("あいうえお", "", "a i u e o", "As cinco vogais na ordem da tabela")]),
      s("Escrever também é observar", "No caderno, acompanhe um traço por vez e repita. Um traço é um movimento feito antes de levantar a caneta. Compare a posição e o tamanho das partes. Nas folhas de impressão, cubra o modelo claro e tente nas casas vazias. A numeração mostra onde cada traço começa.", [], "Não precisa de material especial. Lápis, papel e alguns minutos já servem."),
      s("O romaji é um apoio que você pode retirar", "Romaji representa japonês com letras latinas. Use-o no início e tente escondê-lo quando reconhecer os kana. Para digitar kana, ative um teclado japonês no sistema do seu aparelho: normalmente ka vira か e kka vira っか. Na prática de leitura do Maru, você também pode responder em romaji. A revisão traz de volta os itens que você já praticou.", [e("か", "", "ka", "Digite ka num teclado japonês em modo hiragana."), e("がっこう", "", "gakkō", "escola", "No teclado japonês, gakkou produz a escrita em kana.")])
    ], [q("Qual é um bom começo?", ["Decorar todos os kanji hoje", "Praticar cinco kana e tentar lembrá-los", "Ler apenas romaji para sempre"], 1, "Uma meta pequena deixa espaço para ouvir, escrever e verificar o que você lembra."), q("O que é um traço?", ["Um movimento antes de levantar a caneta", "Uma palavra inteira", "Um som longo"], 0, "Um caractere pode ter vários traços, cada um com uma direção e uma posição."), q("Para que serve a revisão?", ["Para impedir novas lições", "Para apagar erros", "Para reencontrar o que você estudou"], 2, "Voltar a um conteúdo em intervalos ajuda a praticar a lembrança, especialmente nos itens difíceis.")], { route: "worksheets", label: "Preparar uma folha de escrita" })
  ],
  hiragana: [l("h-words", "Dos caracteres às palavras", 7, "Ler pequenas palavras e perceber pausas, combinações e vogais longas.", [
    s("Junte os sons, sem correr", "Em ねこ, leia ね (ne) e こ (ko), depois junte: neko, gato. Não acrescente um som de i após cada consoante como pode acontecer em português. Primeiro leia devagar; depois tente reconhecer a palavra inteira.", [e("ねこ", "", "neko", "gato"), e("いぬ", "", "inu", "cachorro"), e("さかな", "", "sakana", "peixe")]),
    s("Um caractere pequeno pode mudar a palavra", "Compare きや com きゃ. No primeiro, ki e ya têm tempos separados. No segundo, o ゃ pequeno se junta a き: kya ocupa um tempo. Já っ guarda uma pequena pausa antes da consoante seguinte. Em きって, segure brevemente antes do t; não diga tsu.", [e("きって", "", "kitte", "selo"), e("きょう", "", "kyō", "hoje", "きょ forma um som combinado; う prolonga a vogal o.")]),
    s("Observe o tempo extra", "おばさん é tia; おばあさん é avó. O あ extra prolonga a vogal e muda a palavra. Em がっこう, conte quatro tempos: が・っ・こ・う. Repita batendo levemente o dedo. A duração é parte da palavra, não apenas uma maneira de falar mais devagar.", [e("おばさん", "", "obasan", "tia"), e("おばあさん", "", "obāsan", "avó")])
  ], [q("Qual palavra significa gato?", ["ねこ", "いぬ", "さかな"], 0, "ね + こ = neko, gato. いぬ é cachorro e さかな é peixe."), q("Como ler っ em きって?", ["Como tsu completo", "Como uma pausa antes de t", "Como uma vogal longa"], 1, "O っ pequeno ocupa um tempo e prepara a consoante seguinte: kitte."), q("O que muda entre おばさん e おばあさん?", ["Só a letra latina", "Nada na pronúncia", "A duração da vogal e o significado"], 2, "O あ a mais prolonga a vogal: tia e avó são palavras distintas.")], { route: "vocabulary", label: "Ler suas primeiras palavras" }),
  l("h-dialogue", "Uma cena pequena, só em hiragana", 6, "Ler uma cena curta usando apenas hiragana, com apoio de imagens.", [
    s("Duas palavras que você já reconhece", "Antes da cena, veja de novo estas palavras, agora com imagem. Cubra a leitura e tente lembrar antes de olhar.", [e("ねこ", "", "neko", "gato", "", "cat"), e("いぬ", "", "inu", "cachorro", "", "dog")]),
    s("Leia a cena, uma fala de cada vez", "Nenhuma destas frases usa kanji: tudo está em hiragana, como em um livro para quem está começando a ler. Leia devagar, ouça o áudio se precisar e observe as imagens como apoio.", [e("すみません。ねこがいます。", "", "sumimasen. neko ga imasu.", "Com licença. Há um gato.", "", "cat"), e("かわいいですね。", "", "kawaii desu ne.", "Que fofo, né."), e("みずをのみます。", "", "mizu o nomimasu.", "Ele bebe água.", "", "water")]),
    s("Você já lê mais do que imagina", "Se você reconheceu as palavras sem esforço, sua leitura em hiragana está avançando. Se precisou parar em algum ponto, volte e leia a fala de novo antes de seguir: não há pressa.", [], "Tente cobrir a tradução e ler só o hiragana até entender a fala sozinho.")
  ], [
    q("O que すみません。ねこがいます。 informa?", ["Um pedido de silêncio", "Que há um gato", "Que o gato bebeu água"], 1, "すみません chama a atenção; ねこがいます informa que há um gato."),
    q("Qual palavra combina com a imagem de um copo de água?", ["ねこ", "みず", "いぬ"], 1, "みず (mizu) é água. ねこ é gato e いぬ é cachorro."),
    q("かわいいですね expressa…", ["Uma pergunta sobre o preço", "Um comentário de que algo é fofo", "Um pedido para repetir"], 1, "かわいい é fofo/bonitinho; ね convida a outra pessoa a concordar.")
  ], { route: "vocabulary", label: "Reconhecer mais palavras em hiragana" })],
  katakana: [l("k-real-words", "Katakana no mundo real", 6, "Ler palavras adaptadas sem presumir que têm o mesmo sentido do inglês.", [
    s("Reconheça, mas confira", "Katakana adapta palavras aos sons do japonês. カメラ (kamera) é câmera e ホテル (hoteru) é hotel. O empréstimo pode mudar de som e de sentido. マンション costuma se referir a um prédio de apartamentos ou a um apartamento nesse tipo de prédio, não a uma mansão.", [e("カメラ", "", "kamera", "câmera"), e("ホテル", "", "hoteru", "hotel"), e("マンション", "", "manshon", "apartamento / prédio de apartamentos")]),
    s("Palavras também ficam mais curtas", "パソコン vem da expressão adaptada para personal computer e significa computador pessoal. コンビニ abrevia a expressão para loja de conveniência. Não é necessário reconstruir o inglês ao ouvir: aprenda o termo japonês junto com a situação.", [e("パソコン", "", "pasokon", "computador pessoal"), e("コンビニ", "", "konbini", "loja de conveniência")]),
    s("Pequenas vogais ampliam os sons", "ティ combina テ com ィ pequeno para escrever ti. ファ combina フ com ァ para fa. O pequeno caractere modifica o som anterior. カフェ se lê kafe: フェ representa fe. ー prolonga a vogal anterior, como nos dois prolongamentos de コーヒー.", [e("ティー", "", "tī", "chá, em empréstimo usado em nomes e cardápios"), e("カフェ", "", "kafe", "cafeteria"), e("コーヒー", "", "kōhī", "café, a bebida")])
  ], [q("O que significa コンビニ?", ["Convenção", "Loja de conveniência", "Biblioteca"], 1, "É uma abreviação incorporada ao japonês e muito comum para esse tipo de loja."), q("Como se lê ティ?", ["ti", "te-i em dois tempos", "chi"], 0, "ィ pequeno modifica テ para produzir ti."), q("Uma palavra em katakana tem sempre o sentido do inglês?", ["Sim", "Só se for curta", "Não, o significado também pode mudar"], 2, "Aprenda o uso japonês. マンション é um exemplo em que a tradução literal engana.")]),
  l("k-dialogue", "Peça um café, com apoio de imagens", 6, "Ler um pedido curto em uma cafeteria, reconhecendo empréstimos em katakana.", [
    s("Dois empréstimos do cardápio", "コーヒー e ケーキ são escritos em katakana porque vieram de outras línguas. Veja a imagem antes da leitura e tente reconhecer o som.", [e("コーヒー", "", "kōhī", "café", "", "coffee"), e("ケーキ", "", "kēki", "bolo", "", "cake")]),
    s("Um pedido, do início ao fim", "A cena usa katakana para os empréstimos e hiragana para o resto: nenhum kanji ainda. Leia cada fala e imagine a cena em uma cafeteria pequena.", [e("コーヒーをください。", "", "kōhī o kudasai", "Um café, por favor.", "", "coffee"), e("ケーキもいかがですか。", "", "kēki mo ikaga desu ka", "Gostaria de um bolo também?", "", "cake"), e("はい、お願いします。", "はい、おねがいします。", "hai, onegai shimasu", "Sim, por favor.")]),
    s("Reconhecer vem antes de decorar", "Você não precisa memorizar esta cena inteira. O objetivo é reconhecer コーヒー e ケーキ rapidamente, mesmo lendo devagar o resto da frase.", [], "Se quiser mais prática, procure outros empréstimos do dia a dia e tente lê-los em voz alta.")
  ], [
    q("Qual palavra é um empréstimo, escrito em katakana?", ["コーヒー", "ください", "です"], 0, "コーヒー (café) vem de outra língua e por isso é escrita em katakana."),
    q("ケーキもいかがですか pergunta…", ["Se você quer um bolo também", "Se você tem trocado", "Se o café está bom"], 0, "も acrescenta também; いかがですか oferece algo com educação."),
    q("Como aceitar um pedido com educação?", ["いいえ、結構です。", "はい、お願いします。", "さようなら。"], 1, "はい、お願いします aceita o que foi oferecido de forma educada.")
  ], { route: "vocabulary", label: "Reconhecer mais palavras em katakana" })],
  kanji: [l("kanji-parts", "Encontre partes conhecidas", 7, "Usar componentes e palavras como apoio para lembrar kanji, sem adivinhar leituras.", [
    s("Um kanji pode ter peças reconhecíveis", "木 significa árvore. Em 林 e 森, você consegue perceber formas de 木 repetidas. Enxergar componentes ajuda a separar um desenho complexo em partes menores. Isso é uma pista visual; não é uma regra que revela sempre o significado ou a pronúncia.", [e("木", "き", "ki", "árvore"), e("林", "はやし", "hayashi", "bosque"), e("森", "もり", "mori", "floresta")]),
    s("Radical é uma chave de organização", "Dicionários tradicionais agrupam kanji por uma parte chamada radical. Um caractere pode conter vários componentes, mas normalmente tem um radical escolhido para essa classificação. Reconhecer 氵 em palavras ligadas à água pode ajudar; não transforme essa pista em uma tradução automática.", [e("海", "うみ", "umi", "mar", "A parte esquerda 氵 está associada a 水, água.")]),
    s("Aprenda a palavra com a sua leitura", "Em 日本, 日 não é lido hi. A palavra inteira se lê Nihon, Japão. Em 日本語, 語 acrescenta a ideia de língua: Nihongo, japonês. Leia e escreva a palavra junto com o significado. Se memorizar apenas uma leitura por kanji, muitos textos vão parecer contraditórios.", [e("日本", "にほん", "Nihon", "Japão"), e("日本語", "にほんご", "Nihongo", "língua japonesa")])
  ], [q("Reconhecer partes de um kanji ajuda a…", ["Saber sempre a leitura", "Organizar e lembrar a forma", "Dispensar o vocabulário"], 1, "Componentes são apoios visuais, não garantias de leitura e significado."), q("Como se lê 日本語?", ["hi hon go", "ki go", "Nihongo"], 2, "Aprenda a palavra inteira: 日本語, Nihongo, língua japonesa."), q("O radical serve principalmente como…", ["Chave de classificação em dicionários", "Um alfabeto separado", "Uma tradução para português"], 0, "Ele organiza a busca. Nem todo componente reconhecível é o radical de classificação.")])],
  sentences: [
    l("sentence-time", "O que faço, fiz e não faço", 8, "Reconhecer as quatro formas educadas iniciais dos verbos.", [
      s("Uma forma, presente ou futuro", "食べます (tabemasu) pode ser como ou vou comer. O contexto e expressões de tempo indicam quando. O japonês não muda o verbo conforme eu, você ou nós. Aqui vamos partir de formas educadas prontas; aprender a passar de todos os verbos do dicionário para ます exige estudar os grupos verbais depois.", [e("毎日パンを食べます。", "まいにちパンをたべます。", "mainichi pan o tabemasu", "Como pão todos os dias."), e("明日パンを食べます。", "あしたパンをたべます。", "ashita pan o tabemasu", "Vou comer pão amanhã.")]),
      s("Mude a terminação para negar ou falar do passado", "Partindo de 食べます, troque ます por ません para negar: 食べません, não como / não vou comer. Para uma ação passada afirmativa, use ました: 食べました, comi. Para negar no passado, use ませんでした: 食べませんでした, não comi. Isso vale quando você já conhece a forma em ます do verbo.", [e("肉を食べません。", "にくをたべません。", "niku o tabemasen", "Não como carne."), e("昨日パンを食べました。", "きのうパンをたべました。", "kinō pan o tabemashita", "Comi pão ontem."), e("昨日パンを食べませんでした。", "きのうパンをたべませんでした。", "kinō pan o tabemasen deshita", "Não comi pão ontem.")]),
      s("Use as pistas e confirme", "昨日 (kinō) é ontem; 明日 (ashita) é amanhã. Leia a expressão de tempo e depois a terminação. Para perguntar, acrescente か à forma educada. A resposta pode repetir só o verbo, porque a ação já está clara.", [e("朝ご飯を食べましたか。", "あさごはんをたべましたか。", "asagohan o tabemashita ka", "Você tomou café da manhã?"), e("はい、食べました。", "はい、たべました。", "hai, tabemashita", "Sim, comi.")])
    ], [q("Qual forma significa “não comi”?", ["食べます", "食べませんでした", "食べました"], 1, "ませんでした expressa a negação no passado na forma educada."), q("明日パンを食べます se refere a…", ["Amanhã", "Ontem", "Sempre ao passado"], 0, "明日 é amanhã. 食べます pode expressar uma ação futura conforme o contexto."), q("Como perguntar “Você comeu?”?", ["食べますね", "食べませんよ", "食べましたか"], 2, "食べました expressa o passado; か transforma esse enunciado educado em pergunta.")], { route: "exercises", label: "Praticar as formas" }),
    l("sentence-describe", "Descreva o que está à sua volta", 8, "Usar adjetivos em い e em な nos primeiros padrões.", [
      s("Adjetivos acrescentam uma característica", "Grande, gostoso e tranquilo descrevem algo: são adjetivos. Em japonês há dois grupos principais neste começo, chamados adjetivos em い e adjetivos em な. おいしい (oishii) é gostoso; 静か (shizuka) é tranquilo. Você precisa aprender a que grupo a palavra pertence: olhar só a última letra pode enganar.", [e("おいしいです。", "", "oishii desu", "É gostoso."), e("静かです。", "しずかです。", "shizuka desu", "É tranquilo.")]),
      s("Antes de um substantivo, os grupos diferem", "おいしい pode vir diretamente antes de パン: おいしいパン, pão gostoso. Já 静か precisa de な para ligar ao substantivo: 静かな町, cidade tranquila. É desse uso que vem o nome “adjetivo em な”. Ao terminar a frase com です, não coloque な: 静かです.", [e("おいしいパン", "", "oishii pan", "pão gostoso"), e("静かな町", "しずかなまち", "shizuka na machi", "cidade tranquila")]),
      s("Negar também depende do grupo", "Para negar おいしい, retire o い final e use くない: おいしくないです, não é gostoso. Com 静か, use 静かじゃないです, não é tranquilo. いい (bom) é irregular: a negativa é よくないです. Aprenda esses modelos separadamente, sem colocar じゃない depois de todo adjetivo.", [e("このパンはおいしくないです。", "", "kono pan wa oishikunai desu", "Este pão não é gostoso."), e("ここは静かじゃないです。", "ここはしずかじゃないです。", "koko wa shizuka ja nai desu", "Aqui não é tranquilo.")])
    ], [q("Como dizer “cidade tranquila”?", ["静か町", "静かな町", "静かい町"], 1, "静か é do grupo em な: use な para ligá-lo ao substantivo 町."), q("Qual é a negativa de おいしいです?", ["おいしいじゃないです", "おいしいません", "おいしくないです"], 2, "Neste adjetivo em い, o い final dá lugar a くない, seguido de です para o tom educado."), q("Como dizer “É tranquilo”?", ["静かです", "静かなです", "静かいます"], 0, "な faz a ligação antes de um substantivo. Antes de です, use 静かです.")])
  ],
  particles: [l("particle-existence", "Onde está? Onde acontece?", 7, "Diferenciar localização de existência e local da ação com exemplos concretos.", [
    s("Dizer que algo existe", "あります (arimasu) indica a existência de coisas e, normalmente, plantas. います (imasu) indica pessoas e animais. Em 本があります, 本 é o livro cuja existência você informa; が marca esse sujeito. Em 猫がいます, você informa que há um gato.", [e("本があります。", "ほんがあります。", "hon ga arimasu", "Há um livro."), e("猫がいます。", "ねこがいます。", "neko ga imasu", "Há um gato.")]),
    s("に mostra o lugar de existência", "Para dizer onde algo está, coloque o lugar antes de に: ここに本があります, aqui há um livro. ここ significa aqui. O local recebe に porque estamos dizendo onde a coisa existe, não onde uma atividade acontece.", [e("ここに本があります。", "ここにほんがあります。", "koko ni hon ga arimasu", "Há um livro aqui."), e("公園に犬がいます。", "こうえんにいぬがいます。", "kōen ni inu ga imasu", "Há um cachorro no parque.")]),
    s("で mostra onde a ação acontece", "Compare 図書館にいます (estou na biblioteca) com 図書館で読みます (leio na biblioteca). O lugar é o mesmo; o que você quer dizer muda. Não escolha a partícula traduzindo “em”: em português usamos a mesma preposição nos dois casos, mas os padrões japoneses são diferentes.", [e("図書館にいます。", "としょかんにいます。", "toshokan ni imasu", "Estou na biblioteca."), e("図書館で本を読みます。", "としょかんでほんをよみます。", "toshokan de hon o yomimasu", "Leio um livro na biblioteca.")])
  ], [q("Complete: 猫が… (há um gato)", ["あります", "います", "読みます"], 1, "Para a existência de um animal, o padrão básico usa います."), q("Qual partícula indica onde a leitura acontece?", ["で", "を", "の"], 0, "Biblioteca + で + ler. で mostra o local desta ação."), q("Por que não traduzir sempre “em” como に?", ["Porque に não existe", "Porque só vale para pessoas", "Porque a função do lugar na frase muda"], 2, "Existência usa に; uma ação como ler em um lugar usa で. Compare a situação e o verbo.")], { route: "exercises", label: "Escolher as partículas" })],
  everyday: [
    l("daily-numbers", "Preços, horas e quantidades", 8, "Entender que números recebem contadores e reconhecer expressões úteis.", [
      s("Junte números para ler preços", "Depois de um a dez, a composição fica visível: 十一 é dez mais um, jūichi; 二十 é dois vezes dez, nijū. 百 (hyaku) é cem. 円 (en) indica ienes. 三百 tem uma mudança de som: sanbyaku. Aprenda a expressão inteira ao ouvir um preço.", [e("十一", "じゅういち", "jūichi", "onze"), e("二十", "にじゅう", "nijū", "vinte"), e("三百円です。", "さんびゃくえんです。", "sanbyaku en desu", "São trezentos ienes.")]),
      s("Para as horas, acrescente 時", "時 (ji) funciona como um marcador de horas. 三時 é três horas. Algumas leituras são especiais: 四時 se lê yoji, 七時 shichiji e 九時 kuji. 半 (han) indica meia hora. Para perguntar o horário, use 何時 (nanji), que horas.", [e("今、何時ですか。", "いま、なんじですか。", "ima, nanji desu ka", "Que horas são agora?"), e("三時半です。", "さんじはんです。", "sanji han desu", "São três e meia."), e("四時です。", "よじです。", "yoji desu", "São quatro horas.")]),
      s("Contar depende do que está sendo contado", "O japonês usa palavras chamadas contadores com números. Para um pedido simples, ひとつ é uma unidade e ふたつ são duas. Pessoas usam outro contador: ひとり, uma pessoa; ふたり, duas pessoas. Você não precisa decorar todos os contadores agora; comece pelos que aparecem nas situações que pratica.", [e("コーヒーをひとつください。", "", "kōhī o hitotsu kudasai", "Um café, por favor."), e("ふたりです。", "", "futari desu", "Somos duas pessoas.")])
    ], [q("Como se lê 四時?", ["yonji", "yoji", "shiji"], 1, "O horário de quatro horas tem a leitura especial yoji."), q("No restaurante, ふたりです informa…", ["Dois cafés", "Duas horas", "Duas pessoas"], 2, "ふたり conta pessoas. ふたつ é outra expressão, usada para duas unidades."), q("Quanto é 二十?", ["Vinte", "Doze", "Duzentos"], 0, "二 antes de 十 multiplica dez por dois. 十二, na ordem oposta, é doze.")]),
    l("daily-dialogue", "Uma conversa em pequenos turnos", 7, "Combinar cumprimentos, pedidos e respostas em uma conversa curta.", [
      s("Abra espaço para o pedido", "Uma conversa tem turnos: alguém fala, a outra pessoa responde. Ao pedir informação a um desconhecido, すみません chama a atenção com educação. Depois faça a pergunta. Você não precisa dizer “você” em toda frase, porque a pessoa a quem se dirige está clara.", [e("すみません。駅はどこですか。", "すみません。えきはどこですか。", "sumimasen. eki wa doko desu ka", "Com licença. Onde fica a estação?"), e("あそこです。", "", "asoko desu", "É ali.")]),
      s("Confirme ou peça outra tentativa", "Se não entendeu, não precisa fingir que entendeu. もう一度お願いします pede mais uma vez. ゆっくりお願いします pede mais devagar. Depois que a informação fizer sentido, agradeça. Repita estes pequenos blocos até conseguir usá-los sem montar cada palavra.", [e("もう一度お願いします。", "もういちどおねがいします。", "mō ichido onegai shimasu", "Mais uma vez, por favor."), e("ゆっくりお願いします。", "ゆっくりおねがいします。", "yukkuri onegai shimasu", "Devagar, por favor."), e("ありがとうございます。", "", "arigatō gozaimasu", "Muito obrigado(a).")]),
      s("Pratique fazendo os dois papéis", "Leia a pergunta, esconda a resposta e tente responder. Depois troque os papéis. No café: faça o pedido; imagine que a atendente confirma o item; confirme com はい. Essa prática dá contexto a palavras que, isoladas, seriam apenas uma lista.", [e("コーヒーをください。", "", "kōhī o kudasai", "Um café, por favor."), e("コーヒーですね。", "", "kōhī desu ne", "Um café, certo?"), e("はい、お願いします。", "はい、おねがいします。", "hai, onegai shimasu", "Sim, por favor.")])
    ], [q("Como chamar alguém antes de pedir informação?", ["すみません", "じゃあね", "いただきます"], 0, "すみません serve para chamar a atenção educadamente nesta situação."), q("O que fazer se não entendeu?", ["Sempre responder はい", "Usar もう一度お願いします", "Mudar para uma gíria"], 1, "Essa expressão pede repetição e permite continuar a conversa."), q("Em コーヒーですね, ね ajuda a…", ["Negar o café", "Marcar o passado", "Confirmar o pedido com a outra pessoa"], 2, "A atendente apresenta o item como uma informação a confirmar: um café, certo?")], { route: "exercises", label: "Praticar situações" })
  ],
  casual: [
    l("casual-short", "Por que a fala parece tão diferente?", 7, "Reconhecer contrações comuns sem misturar formas casuais e educadas ao acaso.", [
      s("Formas curtas não são só formas educadas sem です", "Entre amigos, 食べます pode aparecer como 食べる (taberu), como / vou comer. 飲みます vira 飲む (nomu). São formas simples do verbo. Não basta cortar ます para formar qualquer verbo casual: 食べ e 飲み não são as formas de dicionário desses verbos.", [e("パンを食べる。", "パンをたべる。", "pan o taberu", "Como / vou comer pão. (casual)"), e("水を飲む。", "みずをのむ。", "mizu o nomu", "Bebo / vou beber água. (casual)")]),
      s("A conversa encurta o que já está claro", "何をしている？ significa “O que você está fazendo?”. Entre amigos, você pode ouvir 何してる？: o を é omitido e している vira してる. ている é uma estrutura que pode indicar uma ação em andamento; por enquanto, reconheça esse exemplo como um bloco de conversa.", [e("何をしている？", "なにをしている？", "nani o shite iru?", "O que você está fazendo? (casual)"), e("何してる？", "なにしてる？", "nani shiteru?", "Tá fazendo o quê? (casual)")]),
      s("Reconheça primeiro, escolha depois", "すみません pode aparecer como すいません na fala. ありがとうございます pode virar o muito informal あざす em certos grupos. Conhecer uma redução ajuda a entender, mas não a torna adequada com qualquer pessoa. Com desconhecidos, continue usando as formas educadas que você já praticou.", [e("すみません", "", "sumimasen", "Com licença / desculpe, forma de referência."), e("あざす", "", "azasu", "Valeu, redução muito informal.")])
    ], [q("A forma de dicionário de 飲みます é…", ["飲み", "飲む", "飲です"], 1, "É 飲む. Não se forma o verbo de dicionário apenas cortando ます."), q("何してる？ é mais adequado…", ["Em um comunicado formal", "Em qualquer situação", "Em conversa casual entre pessoas próximas"], 2, "É uma forma encurtada e informal. O contexto importa tanto quanto o significado."), q("Para que estudar uma redução antes de usá-la?", ["Para entender quando ela aparece", "Para substituir toda forma educada", "Para evitar aprender verbos"], 0, "Seu repertório de compreensão pode ser maior que o conjunto de expressões que você escolhe usar.")]),
    l("casual-communities", "Internet, jogos e trabalho", 6, "Reconhecer jargões pelo ambiente em que aparecem e escolher respostas apropriadas.", [
      s("Uma comunidade cria seu vocabulário", "Jargão é vocabulário associado a uma atividade. Em jogos, 初見 indica ver ou fazer algo pela primeira vez; em uma transmissão pode identificar quem chegou pela primeira vez. 攻略 é estratégia ou guia para avançar. Aprenda o ambiente junto com a palavra para não tratar todo termo como gíria universal.", [e("初見", "しょけん", "shoken", "primeira vez vendo / primeiro contato"), e("攻略", "こうりゃく", "kōryaku", "estratégia / guia para avançar em um jogo")]),
      s("Escrito e falado nem sempre coincidem", "草 pode representar risada na internet. Literalmente, kusa é grama. ネタバレ é spoiler e 配信 é transmissão ou distribuição de conteúdo. Você pode entender uma reação escrita sem reproduzi-la em uma conversa com professor ou cliente.", [e("草", "くさ", "kusa", "risada em certos contextos de internet"), e("配信", "はいしん", "haishin", "transmissão / distribuição de conteúdo"), e("ネタバレ注意", "ネタバレちゅうい", "netabare chūi", "atenção: spoilers")]),
      s("No trabalho, a relação também orienta a escolha", "お疲れさまです reconhece o esforço e funciona como saudação entre colegas. Para confirmar uma instrução de cliente ou superior, 承知しました é uma opção educada. Não traduza essas fórmulas palavra por palavra: aprenda quem fala, para quem e em qual momento.", [e("お疲れさまです。", "おつかれさまです。", "otsukaresama desu", "Saudação de reconhecimento do esforço entre colegas."), e("承知しました。", "しょうちしました。", "shōchi shimashita", "Entendido. (educado)")])
    ], [q("Jargão está ligado principalmente a…", ["Uma atividade ou comunidade", "Uma escrita sem kana", "Qualquer fala rude"], 0, "Pode aparecer em jogos, trabalho e outras áreas. Não é sinônimo de palavrão."), q("ネタバレ注意 avisa sobre…", ["Um atraso", "Uma refeição", "Spoilers"], 2, "ネタバレ é spoiler e 注意 pede atenção."), q("Qual resposta é uma opção educada para confirmar uma instrução?", ["草", "承知しました", "マジ？"], 1, "承知しました confirma entendimento com educação. As outras opções pertencem a situações informais diferentes.")], { route: "expressions", label: "Explorar expressões em contexto" })
  ]
};
