export const VOCABULARY_GROUPS = [
  ["all", "Todas as palavras"], ["people", "Pessoas"], ["food", "Comida e bebida"], ["places", "Lugares"],
  ["things", "Objetos e natureza"], ["actions", "Ações"], ["time", "Tempo e rotina"], ["qualities", "Características"]
];

const word = (id, group, jp, reading, romaji, pt, sentence, sentenceReading, sentenceRomaji, translation, note = "") =>
  ({ id: "word-" + id, group, jp, reading, romaji, pt, sentence, sentenceReading, sentenceRomaji, translation, note });

export const VOCABULARY = [
  word("me", "people", "私", "わたし", "watashi", "eu", "私は学生です。", "わたしはがくせいです。", "watashi wa gakusei desu", "Eu sou estudante.", "Quando o contexto já deixa claro quem fala, 私 pode ser omitido."),
  word("friend", "people", "友達", "ともだち", "tomodachi", "amigo(a)", "友達と話します。", "ともだちとはなします。", "tomodachi to hanashimasu", "Converso com um amigo.", "と mostra com quem a conversa acontece."),
  word("teacher", "people", "先生", "せんせい", "sensei", "professor(a)", "田中さんは先生です。", "たなかさんはせんせいです。", "Tanaka-san wa sensei desu", "Tanaka é professor(a).", "先生 também pode ser usado como título em algumas profissões."),
  word("student", "people", "学生", "がくせい", "gakusei", "estudante", "私は学生です。", "わたしはがくせいです。", "watashi wa gakusei desu", "Eu sou estudante."),
  word("family", "people", "家族", "かぞく", "kazoku", "família", "家族と食べます。", "かぞくとたべます。", "kazoku to tabemasu", "Como com a minha família."),
  word("mother", "people", "母", "はは", "haha", "minha mãe", "母は先生です。", "はははせんせいです。", "haha wa sensei desu", "Minha mãe é professora.", "Ao falar da própria mãe para alguém de fora da família. お母さん é comum ao chamá-la ou ao falar da mãe de outra pessoa."),
  word("father", "people", "父", "ちち", "chichi", "meu pai", "父は会社員です。", "ちちはかいしゃいんです。", "chichi wa kaishain desu", "Meu pai é funcionário de uma empresa.", "Ao falar do próprio pai para alguém de fora da família. Ao chamá-lo, お父さん é comum."),
  word("person", "people", "人", "ひと", "hito", "pessoa", "あの人は先生です。", "あのひとはせんせいです。", "ano hito wa sensei desu", "Aquela pessoa é professor(a)."),
  word("water", "food", "水", "みず", "mizu", "água", "水を飲みます。", "みずをのみます。", "mizu o nomimasu", "Bebo água.", "を mostra o que é bebido."),
  word("tea", "food", "お茶", "おちゃ", "ocha", "chá", "お茶をください。", "おちゃをください。", "ocha o kudasai", "Chá, por favor."),
  word("coffee", "food", "コーヒー", "コーヒー", "kōhī", "café", "コーヒーを飲みます。", "コーヒーをのみます。", "kōhī o nomimasu", "Bebo café.", "Os dois sinais ー prolongam as vogais: kō e hī."),
  word("bread", "food", "パン", "パン", "pan", "pão", "パンを食べます。", "パンをたべます。", "pan o tabemasu", "Como pão."),
  word("rice", "food", "ご飯", "ごはん", "gohan", "arroz cozido / refeição", "ご飯を食べます。", "ごはんをたべます。", "gohan o tabemasu", "Como arroz / faço uma refeição.", "O sentido depende do contexto. Não é arroz cru, que se chama 米 (こめ)."),
  word("sushi", "food", "すし", "すし", "sushi", "sushi", "すしが好きです。", "すしがすきです。", "sushi ga suki desu", "Gosto de sushi."),
  word("fish", "food", "魚", "さかな", "sakana", "peixe", "魚を食べます。", "さかなをたべます。", "sakana o tabemasu", "Como peixe."),
  word("meat", "food", "肉", "にく", "niku", "carne", "肉を買います。", "にくをかいます。", "niku o kaimasu", "Compro carne."),
  word("apple", "food", "りんご", "りんご", "ringo", "maçã", "りんごを食べます。", "りんごをたべます。", "ringo o tabemasu", "Como uma maçã."),
  word("milk", "food", "牛乳", "ぎゅうにゅう", "gyūnyū", "leite de vaca", "牛乳を飲みます。", "ぎゅうにゅうをのみます。", "gyūnyū o nomimasu", "Bebo leite."),
  word("egg", "food", "卵", "たまご", "tamago", "ovo", "卵を買います。", "たまごをかいます。", "tamago o kaimasu", "Compro ovos."),
  word("cake", "food", "ケーキ", "ケーキ", "kēki", "bolo", "このケーキはおいしいです。", "このケーキはおいしいです。", "kono kēki wa oishii desu", "Este bolo é gostoso."),
  word("home", "places", "家", "いえ", "ie", "casa", "家に帰ります。", "いえにかえります。", "ie ni kaerimasu", "Volto para casa."),
  word("school", "places", "学校", "がっこう", "gakkō", "escola", "学校に行きます。", "がっこうにいきます。", "gakkō ni ikimasu", "Vou para a escola.", "O pequeno っ prepara o fechamento antes do k. O おう final é uma vogal longa."),
  word("station", "places", "駅", "えき", "eki", "estação", "駅はどこですか。", "えきはどこですか。", "eki wa doko desu ka", "Onde fica a estação?"),
  word("library", "places", "図書館", "としょかん", "toshokan", "biblioteca", "図書館で勉強します。", "としょかんでべんきょうします。", "toshokan de benkyō shimasu", "Estudo na biblioteca."),
  word("park", "places", "公園", "こうえん", "kōen", "parque", "公園に行きます。", "こうえんにいきます。", "kōen ni ikimasu", "Vou ao parque."),
  word("shop", "places", "店", "みせ", "mise", "loja", "この店は安いです。", "このみせはやすいです。", "kono mise wa yasui desu", "Esta loja é barata."),
  word("bathroom", "places", "トイレ", "トイレ", "toire", "banheiro", "トイレはどこですか。", "トイレはどこですか。", "toire wa doko desu ka", "Onde fica o banheiro?"),
  word("japan", "places", "日本", "にほん", "Nihon", "Japão", "日本に行きます。", "にほんにいきます。", "Nihon ni ikimasu", "Vou ao Japão.", "Nippon (にっぽん) também é uma leitura de 日本."),
  word("brazil", "places", "ブラジル", "ブラジル", "Burajiru", "Brasil", "ブラジルから来ました。", "ブラジルからきました。", "Burajiru kara kimashita", "Vim do Brasil."),
  word("convenience", "places", "コンビニ", "コンビニ", "konbini", "loja de conveniência", "コンビニで水を買います。", "コンビニでみずをかいます。", "konbini de mizu o kaimasu", "Compro água na loja de conveniência."),
  word("book", "things", "本", "ほん", "hon", "livro", "本を読みます。", "ほんをよみます。", "hon o yomimasu", "Leio um livro."),
  word("cat", "things", "猫", "ねこ", "neko", "gato", "猫がいます。", "ねこがいます。", "neko ga imasu", "Há um gato."),
  word("dog", "things", "犬", "いぬ", "inu", "cachorro", "犬がいます。", "いぬがいます。", "inu ga imasu", "Há um cachorro."),
  word("mountain", "things", "山", "やま", "yama", "montanha", "山に行きます。", "やまにいきます。", "yama ni ikimasu", "Vou à montanha."),
  word("river", "things", "川", "かわ", "kawa", "rio", "川があります。", "かわがあります。", "kawa ga arimasu", "Há um rio."),
  word("tree", "things", "木", "き", "ki", "árvore", "木があります。", "きがあります。", "ki ga arimasu", "Há uma árvore."),
  word("phone", "things", "電話", "でんわ", "denwa", "telefone / ligação", "電話を使います。", "でんわをつかいます。", "denwa o tsukaimasu", "Uso o telefone."),
  word("train", "things", "電車", "でんしゃ", "densha", "trem", "電車で行きます。", "でんしゃでいきます。", "densha de ikimasu", "Vou de trem.", "Aqui で indica o meio de transporte."),
  word("umbrella", "things", "傘", "かさ", "kasa", "guarda-chuva", "傘を買います。", "かさをかいます。", "kasa o kaimasu", "Compro um guarda-chuva."),
  word("music", "things", "音楽", "おんがく", "ongaku", "música", "音楽を聞きます。", "おんがくをききます。", "ongaku o kikimasu", "Ouço música."),
  word("eat", "actions", "食べる", "たべる", "taberu", "comer", "パンを食べます。", "パンをたべます。", "pan o tabemasu", "Como pão.", "食べる é a forma de dicionário; 食べます é a forma educada."),
  word("drink", "actions", "飲む", "のむ", "nomu", "beber", "水を飲みます。", "みずをのみます。", "mizu o nomimasu", "Bebo água.", "Aprenda o par 飲む → 飲みます. Não basta colar ます à forma do dicionário."),
  word("go", "actions", "行く", "いく", "iku", "ir", "学校に行きます。", "がっこうにいきます。", "gakkō ni ikimasu", "Vou para a escola."),
  word("come", "actions", "来る", "くる", "kuru", "vir", "友達が来ます。", "ともだちがきます。", "tomodachi ga kimasu", "Um amigo vem.", "来る é irregular: くる vira きます na forma educada."),
  word("read", "actions", "読む", "よむ", "yomu", "ler", "本を読みます。", "ほんをよみます。", "hon o yomimasu", "Leio um livro."),
  word("write", "actions", "書く", "かく", "kaku", "escrever", "名前を書きます。", "なまえをかきます。", "namae o kakimasu", "Escrevo meu nome."),
  word("hear", "actions", "聞く", "きく", "kiku", "ouvir / perguntar", "音楽を聞きます。", "おんがくをききます。", "ongaku o kikimasu", "Ouço música.", "聞く também pode ser perguntar. Observe a frase em que aparece."),
  word("speak", "actions", "話す", "はなす", "hanasu", "falar / conversar", "日本語を話します。", "にほんごをはなします。", "nihongo o hanashimasu", "Falo japonês."),
  word("buy", "actions", "買う", "かう", "kau", "comprar", "本を買います。", "ほんをかいます。", "hon o kaimasu", "Compro um livro."),
  word("study", "actions", "勉強する", "べんきょうする", "benkyō suru", "estudar", "日本語を勉強します。", "にほんごをべんきょうします。", "nihongo o benkyō shimasu", "Estudo japonês."),
  word("today", "time", "今日", "きょう", "kyō", "hoje", "今日は休みです。", "きょうはやすみです。", "kyō wa yasumi desu", "Hoje é dia de folga."),
  word("tomorrow", "time", "明日", "あした", "ashita", "amanhã", "明日、学校に行きます。", "あした、がっこうにいきます。", "ashita, gakkō ni ikimasu", "Amanhã vou para a escola."),
  word("yesterday", "time", "昨日", "きのう", "kinō", "ontem", "昨日、本を読みました。", "きのう、ほんをよみました。", "kinō, hon o yomimashita", "Ontem li um livro."),
  word("now", "time", "今", "いま", "ima", "agora", "今、勉強しています。", "いま、べんきょうしています。", "ima, benkyō shite imasu", "Agora estou estudando."),
  word("everyday", "time", "毎日", "まいにち", "mainichi", "todos os dias", "毎日、日本語を勉強します。", "まいにち、にほんごをべんきょうします。", "mainichi, nihongo o benkyō shimasu", "Estudo japonês todos os dias."),
  word("morning", "time", "朝", "あさ", "asa", "manhã", "朝、パンを食べます。", "あさ、パンをたべます。", "asa, pan o tabemasu", "De manhã, como pão."),
  word("night", "time", "夜", "よる", "yoru", "noite", "夜、本を読みます。", "よる、ほんをよみます。", "yoru, hon o yomimasu", "À noite, leio um livro."),
  word("weekend", "time", "週末", "しゅうまつ", "shūmatsu", "fim de semana", "週末、公園に行きます。", "しゅうまつ、こうえんにいきます。", "shūmatsu, kōen ni ikimasu", "No fim de semana, vou ao parque."),
  word("delicious", "qualities", "おいしい", "おいしい", "oishii", "gostoso / delicioso", "このパンはおいしいです。", "このパンはおいしいです。", "kono pan wa oishii desu", "Este pão é gostoso."),
  word("big", "qualities", "大きい", "おおきい", "ōkii", "grande", "大きい犬です。", "おおきいいぬです。", "ōkii inu desu", "É um cachorro grande."),
  word("small", "qualities", "小さい", "ちいさい", "chiisai", "pequeno", "小さい猫です。", "ちいさいねこです。", "chiisai neko desu", "É um gato pequeno."),
  word("cheap", "qualities", "安い", "やすい", "yasui", "barato", "この本は安いです。", "このほんはやすいです。", "kono hon wa yasui desu", "Este livro é barato."),
  word("fun", "qualities", "楽しい", "たのしい", "tanoshii", "divertido / prazeroso", "日本語の勉強は楽しいです。", "にほんごのべんきょうはたのしいです。", "nihongo no benkyō wa tanoshii desu", "Estudar japonês é divertido."),
  word("quiet", "qualities", "静か", "しずか", "shizuka", "tranquilo / silencioso", "静かな場所です。", "しずかなばしょです。", "shizuka na basho desu", "É um lugar tranquilo.", "静か usa な antes de um substantivo: 静かな場所.")
];
